'use strict';
const express=require('express');const path=require('path');const fs=require('fs');const cors=require('cors');const{OpenAI}=require('openai');require('dotenv').config();
const app=express(),PORT=process.env.PORT||3000,PUBLIC=path.join(__dirname,'public'),DATA=path.join(PUBLIC,'data');const openai=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
app.disable('x-powered-by');app.use(cors());app.use(express.json({limit:'700kb'}));
function profile(id='le-hoan'){const p=path.join(DATA,`${String(id).replace(/[^a-z0-9-]/gi,'')}.json`);if(!fs.existsSync(p))return null;return JSON.parse(fs.readFileSync(p,'utf8'))}
function ctx(p,lang='vi'){const en=lang==='en';const facts=p.facts.map(f=>`[${f.sources.join(',')}] ${en?f.en:f.vi}`).join('\n');const sources=p.sources.map(s=>`${s.id}: ${en?s.titleEn:s.title}`).join('\n');return `${en?'HISTORICAL FIGURE':'NHÂN VẬT'}: ${en?p.nameEn:p.name}\n${en?'CURATED FACTS':'DỮ KIỆN NỀN'}:\n${facts}\n${en?'ALLOWED SOURCES':'NGUỒN ĐƯỢC PHÉP'}:\n${sources}\n${en?'Only use these curated facts as established background. If information is not supported, say verification is needed. Never invent sources, quotations, dates or numbers.':'Chỉ dùng các dữ kiện nền này như thông tin chắc chắn. Nếu chưa đủ dữ liệu phải nói cần kiểm chứng. Không bịa nguồn, trích dẫn, ngày tháng hay con số.'}`}
function clean(v,n=1200){return String(v??'').trim().slice(0,n)}function hist(v){return Array.isArray(v)?v.slice(-14).map(x=>({role:x.role==='assistant'?'assistant':'user',content:clean(x.content,4000)})):[]}
async function jsonChat(messages,temp=.4){const r=await openai.chat.completions.create({model:process.env.OPENAI_TEXT_MODEL||'gpt-4o-mini',messages,temperature:temp,response_format:{type:'json_object'}});return JSON.parse(r.choices[0].message.content)}
app.get('/health',(_,res)=>res.json({ok:true,aiReady:Boolean(process.env.OPENAI_API_KEY)}));
app.post('/ask',async(req,res)=>{const p=profile(req.body.characterId);if(!p)return res.status(400).json({message:'Character not configured'});const q=clean(req.body.question,600),lang=req.body.lang==='en'?'en':'vi';try{const prompt=`${ctx(p,lang)}\n${lang==='en'?'Answer entirely in English.':'Trả lời hoàn toàn bằng tiếng Việt.'}\nYou are a historical inquiry assistant. Return JSON exactly with keys: answerType, reply, evidencePoints (array), sourceIds (array), evidenceNote, confidence, suggestions (array). If the question is a what-if scenario, tell the learner to use counterfactual analysis.`;const d=await jsonChat([{role:'system',content:prompt},{role:'user',content:q}],.3);res.json(d)}catch(e){res.status(500).json({message:lang==='en'?'AI inquiry is unavailable.':'Tra cứu AI đang tạm gián đoạn.'})}});
app.post('/whatif',async(req,res)=>{const p=profile(req.body.characterId),lang=req.body.lang==='en'?'en':'vi';if(!p)return res.status(400).json({message:'Character not configured'});try{const prompt=`${ctx(p,lang)}\n${lang==='en'?'Write entirely in English.':'Viết hoàn toàn bằng tiếng Việt.'}\nGuide counterfactual historical thinking. Return JSON with baseline, sourceIds, changedAssumption, consequences (3-5 strings), uncertainty, methodNote, impact, suggestions. Never give fake success rates, casualty percentages or invented quantitative predictions.`;res.json(await jsonChat([{role:'system',content:prompt},...hist(req.body.history),{role:'user',content:clean(req.body.scenario,700)}],.5))}catch(e){res.status(500).json({message:lang==='en'?'Counterfactual analysis is unavailable.':'Phân tích giả định đang tạm gián đoạn.'})}});
app.post('/roleplay',async(req,res)=>{const p=profile(req.body.characterId),lang=req.body.lang==='en'?'en':'vi',turn=Math.max(1,Number(req.body.turn||1));if(!p)return res.status(400).json({message:'Character not configured'});try{const prompt=`${ctx(p,lang)}\n${lang==='en'?'Write entirely in English.':'Viết hoàn toàn bằng tiếng Việt.'}\nHistorical decision role-play, turn ${turn}/6. The learner plays Le Hoan in an educational simulation around 980-981. Return JSON: npcDialogue, feedback, sourceIds, choices (exactly 3 unless game over), isGameOver, endReason. Consider military, diplomacy, public support and logistics. Source IDs only support real background, not simulated events. End at turn 6.`;const d=await jsonChat([{role:'system',content:prompt},...hist(req.body.history)],.6);if(turn>=6){d.isGameOver=true;d.choices=[]}res.json(d)}catch(e){res.status(500).json({message:lang==='en'?'Role-play is unavailable.':'Nhập vai đang tạm gián đoạn.'})}});
app.post('/speak',async(req,res)=>{const text=clean(req.body.text,3500),lang=req.body.lang==='en'?'en':'vi';if(!text)return res.status(400).end();try{const a=await openai.audio.speech.create({model:process.env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',voice:lang==='vi'?'cedar':'marin',input:text,instructions:lang==='vi'?'Đọc tiếng Việt rõ ràng, nhịp vừa, giọng thuyết minh lịch sử trang trọng nhưng gần gũi.':'Read clearly at a moderate pace in a calm museum-guide tone.',response_format:'mp3'});res.type('audio/mpeg').send(Buffer.from(await a.arrayBuffer()))}catch(e){res.status(500).end()}});
app.post('/save-report',async(req,res)=>{const url=process.env.GOOGLE_SHEET_URL;if(!url)return res.json({success:false,message:'GOOGLE_SHEET_URL missing'});try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(req.body),redirect:'follow'});res.json({success:r.ok})}catch(e){res.status(502).json({success:false})}});
app.use(express.static(PUBLIC,{index:'index.html',setHeaders(res,file){if(file.endsWith('.glb'))res.setHeader('Content-Type','model/gltf-binary')}}));app.listen(PORT,()=>console.log(`Server running on http://localhost:${PORT}`));
